sonar.projectKey=mayaralabidi_SkillForTat
sonar.organization=mayoitbs
sonar.projectName=My DevOps App

sonar.sources=skillfortat-client/src,skillfortat-server/src
sonar.tests=skillfortat-client/src,skillfortat-server/src
sonar.javascript.lcov.reportPaths=skillfortat-client/coverage/lcov.info,skillfortat-server/coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=false